### PR TITLE
Convert event parameters from LCIO to EDM4hep

### PR DESCRIPTION
**Pull request by Zehvogel**
BEGINRELEASENOTES
- Add lcio to edm4hep event parameter conversion

ENDRELEASENOTES

- [x] depends-on: https://github.com/key4hep/k4FWCore/pull/194

### CODE REVIEW

**Comment by tmadlener** [comment]
Technically, I think the `const_cast` should be OK in this case as the original Frame is not `const`. Additionally, the underlying `putParameter` (and the `GenericParameters`) are thread safe (via locking). From that point of view the `PodioDataSvc` could in principle also hand out a mutable Frame via `getEventFrame`.

**Comment by Zehvogel** [comment]
Yes I mainly meant it has to go as I would consider it ugly...

I am in favour of returning a non-const frame to get rid of this quickly. :)

I am not so sure about the sustainability in the long run though. The whole being able to access the frame directly via the datasvc from any Algorithm leads the whole concept of Algorithms having to specify in-/output collections ad absurdum, doesn't it?

**Comment by tmadlener** [comment]
> I am not so sure about the sustainability in the long run though. The whole being able to access the frame directly via the datasvc from any Algorithm leads the whole concept of Algorithms having to specify in-/output collections ad absurdum, doesn't it?

Yes, fully agree. I am not sure if there is an easier way at the moment. In principle I think only the MarlinWrapper currently needs these special accesses. But that will probably also be around for quite some time.

**Comment by Zehvogel** [comment]
can someone re-trigger the ci pls? :)

**Comment by andresailer** [comment]
Can you not?

**Comment by Zehvogel** [comment]
> Can you not?

No, and I think it is not only because I am too blind to find the button...

**Comment by andresailer** [comment]
> > Can you not?
> 
> No, and I think it is not only because I am too blind to find the button...

True, https://docs.github.com/en/actions/managing-workflow-runs/re-running-workflows-and-jobs

But the jobs still fail.

**Comment by Zehvogel** [comment]
Oh yes, the merge this morning just felt so far away that I thought it was yesterday... it will take another day until the nightlies picked it up :(

**Review by tmadlener — APPROVED** [review]

**Pull request merged**
