### PR TITLE
Don't use GaudiAlg

### PR DESCRIPTION
**Pull request by jmcarcell**
BEGINRELEASENOTES
- Change headers and add EventContext in algorithms not to use GaudiAlg
- Replace `GaudiTool` with `AlgTool`

ENDRELEASENOTES

### CODE REVIEW

**Comment by andresailer** [comment]
This is still work in progress or depend on some other PR?

**Comment by jmcarcell** [comment]
This should now be ready, finally the build is passing

**Review by tmadlener — COMMENTED** [review]
Do I have to understand why `AlgTool` is the non-deprecated on while `GaudiTool` is? ;)

This looks fairly complete now, or is there still something missing?

**Comment by jmcarcell** [comment]
> Do I have to understand why `AlgTool` is the non-deprecated on while `GaudiTool` is? ;)
`GaudiTool` is in `GaudiAlg` :smile: 
I think there are a few differences like `AlgTool` not accessing the data store directly. In general I think we use few things of the class and we could probably get by with a minimal implementation of `IAlgTool`.

> This looks fairly complete now, or is there still something missing?
It's ready, I don't think anything needs to be changed unless we find issues but the tests are passing.

**Review by tmadlener — APPROVED** [review]

**Pull request merged**
