### PR TITLE
[clang-format] Fix formatting

### PR DESCRIPTION
**Pull request by tmadlener**
BEGINRELEASENOTES
- Fix formatting

ENDRELEASENOTES

Fixing formatting in a separate PR here to get the `clang-format-check` workflow working properly again and to declutter other PRs

### CODE REVIEW

**Comment by andresailer** [comment]
The error in the edm_coverters test is caused by the LCIO Tracks being converted before the LCIO TrackerHit collection, and then there are no TrackerHits in the the EDM4hep Track Collection

**Comment by andresailer** [comment]
This https://github.com/key4hep/k4LCIOReader/pull/28 is causing the problem in the edm_converters

**Comment by tmadlener** [comment]
Hasn't this been working with that changes in place already in the past?

**Comment by andresailer** [comment]
At least the test probably hasn't worked. If I revert that commit and run the test, the test passes.

**Comment by andresailer** [comment]
What I don't understand is that even with
https://github.com/key4hep/k4MarlinWrapper/blob/b2b6816091c95046e2b03b3a5105ede6da530a8c/test/gaudi_opts/edm_converters.py#L30
the test passes with the changes in k4LCIOReader I propose in https://github.com/key4hep/k4LCIOReader/pull/30

**Comment by tmadlener** [comment]
Since the long-term solution would be to replace the `k4LCIOReader` here with key4hep/k4EDM4hep2LcioConv#11 in any case, should we try that already now?

**Review by andresailer — APPROVED** [review]
Since this is just changing format, and the test error is hopefully solved, let's merge

**Pull request merged**
