### PR TITLE
Fix a few warnings when compiling

### PR DESCRIPTION
**Pull request by jmcarcell**
BEGINRELEASENOTES
- Fix warnings after https://github.com/key4hep/EDM4hep/pull/315
- Fix a warning by adding a default case in a switch statement

ENDRELEASENOTES

### CODE REVIEW

**Review by tmadlener — APPROVED** [review]
Is this currently warning free? Then we could  consider adding `-Werror` to CI to keep it that way? But I suppose that would need to go into the key4hep build action, right?

**Comment by jmcarcell** [comment]
I don't get any warnings with this change. Adding `-Werror` won't work for `k4EDM4hep2LcioConv` so I can't add it globally yet but I'm not opposed to have it or at least try it for some time. It may be annoying when changing compiler or version and finding that a warning appears though.

**Comment by tmadlener** [comment]
Maybe it could be an option of the action? Then it would be easier to toggle on a per project basis. Maybe we need to take the discussion to the correct repo. I will merge this now.

**Comment by jmcarcell** [comment]
Tagging @Zehvogel since he has complained about message verbosity; this change will modify the cases when the Gaudi message level is set to `NIL, VERBOSE, FATAL, ALWAYS, NUM_LEVELS` (see https://gitlab.cern.ch/gaudi/Gaudi/-/blob/master/install/include/GaudiKernel/IMessageSvc.h#L25), since these were not in the switch statement. At the very least `m_level` is set by default to `NIL` https://gitlab.cern.ch/gaudi/Gaudi/-/blob/master/install/include/GaudiKernel/CommonMessaging.h#L130. I think this may change the default when no verbosity is set since it's `ERROR` https://github.com/key4hep/k4MarlinWrapper/blob/main/k4MarlinWrapper/k4MarlinWrapper/MarlinProcessorWrapper.h#L68 and after this it will be `MESSAGE`.

**Pull request merged**
