### PR TITLE
[WIP] Use k4EDM4hep2LcioConv as separate lib

### PR DESCRIPTION
**Pull request by fdplacido**
BEGINRELEASENOTES
- Use k4EDM4hep2LcioConv as separate lib
- Remove conversion from MarlinWrapper

ENDRELEASENOTES

- Needs https://github.com/key4hep/k4EDM4hep2LcioConv/ to be in CVMFS

### CODE REVIEW

**Comment by fdplacido** [comment]
The test seems to be failing due to a symbol mismatch between the k4edm4hep2lcioconv library and what is looking for.

The library in CVMFS contains the following:
```sh
$ [plfernan:~/ws/k4MarlinWrapper/build] $ nm /cvmfs/sw-nightlies.hsf.org/spackages5/k4edm4hep2lcioconv/00-01/x86_64-centos7-gcc11.2.0-opt/zaozb/lib64/libk4EDM4hep2LcioConv.so | rg collection | c++filt
0000000000010580 T collectionExist(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, IMPL::LCEventImpl const*)
```

But the error is looking for: 
```
python: symbol lookup error: /k4MW/install/lib64/libEDM4hep2Lcio.so: undefined symbol: _Z15collectionExistRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEPN4IMPL11LCEventImplE
```

which is:

```
$ c++filt _Z15collectionExistRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEPN4IMPL11LCEventImplE
collectionExist(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, IMPL::LCEventImpl*)
```

**Comment by andresailer** [comment]
For some reason this mismatch isn't causing a problem in the library itself:
https://github.com/key4hep/k4EDM4hep2LcioConv/blob/e2739750d1f0442f41533f61d02fe662084fe802/k4EDM4hep2LcioConv/include/k4EDM4hep2LcioConv/k4EDM4hep2LcioConv.h#L145
vs
https://github.com/key4hep/k4EDM4hep2LcioConv/blob/e2739750d1f0442f41533f61d02fe662084fe802/k4EDM4hep2LcioConv/src/k4EDM4hep2LcioConv.cpp#L838

**Comment by fdplacido** [comment]
> For some reason this mismatch isn't causing a problem in the library itself: https://github.com/key4hep/k4EDM4hep2LcioConv/blob/e2739750d1f0442f41533f61d02fe662084fe802/k4EDM4hep2LcioConv/include/k4EDM4hep2LcioConv/k4EDM4hep2LcioConv.h#L145 vs https://github.com/key4hep/k4EDM4hep2LcioConv/blob/e2739750d1f0442f41533f61d02fe662084fe802/k4EDM4hep2LcioConv/src/k4EDM4hep2LcioConv.cpp#L838

I changed the header signature to also have `const`, hopefully that fixes it.

**Comment by vvolkl** [comment]
Works with the nightlies now. I'd suggest to make a patch release for the converter library.

**Comment by fdplacido** [comment]
> Works with the nightlies now. I'd suggest to make a patch release for the converter library.

yeah, I will create a new release and then we can merge this.

**Pull request merged**
