### PR TITLE
Don't use run to run k4run

### PR DESCRIPTION
**Pull request by jmcarcell**
BEGINRELEASENOTES
- Remove run (autogenerated script to set up the environment) from some tests that use it together with k4run; we should set up the environment either in `CMakeLists.txt` or externally. 

ENDRELEASENOTES

Either we set the environment externally or in CMakeLists.txt but don't use run and force some relative paths that may or may not be how it is built. I tested this and both test work fine

### CODE REVIEW

**Comment by andresailer** [comment]
Can you please elaborate more on the release notes?

**Comment by jmcarcell** [comment]
Done. CI is failing but the two tests that this is changing succeeded

**Comment by tmadlener** [comment]
who or what generates the `run` script? If it is no longer necessary can it be removed?

**Comment by jmcarcell** [comment]
That comes from Gaudi: https://gitlab.cern.ch/gaudi/Gaudi/-/blob/master/cmake/GaudiToolbox.cmake#L1546
Probably people rely on this so it's not easy to have it removed. It doesn't hurt either, it's just there if we don't use it.
This is the only issue I found about this: https://gitlab.cern.ch/gaudi/Gaudi/-/issues/183

**Comment by jmcarcell** [comment]
Ahah now one the tests that succeeded in the checks in this PR and also after https://github.com/key4hep/k4MarlinWrapper/pull/114 fails, of course

**Pull request merged**
